### ISSUE TITLE
Problem iOS build

### ISSUE THREAD

**Issue by ingouackaz** [samizzo/UnityNativePrototype#2]
Hi guys !

A great thanks for the works you are doing, this is exactly what i am looking for !

However i have some trouble with the iOS compilation :/ , is it possible to have more screenshot or a short video in which i can precisely watch and understand, how do you do ?

Thanks :)

**Comment by samizzo** [comment]
Just for visibility, I'm adding the info from your email here:
I am using Xcode 7.0 With Unity 5.2.0f3 and the Error message is 

```
ld: warning: ignoring file /Users/ingouackaz/Downloads/UnityNativePrototype-master/UnityProject/UnityProject/Libraries/Plugins/iOS/libNativeProjectLib.a, file was built for archive which is not the architecture being linked (arm64): /Users/ingouackaz/Downloads/UnityNativePrototype-master/UnityProject/UnityProject/Libraries/Plugins/iOS/libNativeProjectLib.a

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_NativeInterface", referenced from:"
```

**Comment by samizzo** [comment]
I've pushed some changes to hopefully get this working in 5.2.1f1. I've rebuilt the sample static library and set the projects to build for arm64. It seems like that might be why it wasn't working for you. It works for me in the simulator now but I haven't yet been able to test on a device because I don't have my cable handy.

**Comment by ingouackaz** [comment]
Same error :( 

In fact I have difficulty to determine if your tutorial explains how your library works and the sample is here  test your lib, or if I'm supposed to made changes in your sample ?

Suppose that from your example I would simply test the iOS app and if I press the button "Switch to Unity .." I am redirected to the page Unity and vice versa.

What part of the tutorial should I follow?

**Comment by ingouackaz** [comment]
@samizzo it works :+1:  
Thanks you very much !

The problems come from libNativeProjectLib.a

I I've just rebuilt the sample static library myself :)

**Comment by samizzo** [comment]
That's great to hear! Yeah the sample should work in theory! Maybe I checked in the wrong static lib.

**Comment by ingouackaz** [comment]
@samizzo  after another long research ... i realized that the problem comes from the Unity Build and not static Library.

After the Unity build for iOS we have this in build setting.

![badbuilds](https://cloud.githubusercontent.com/assets/3285421/10363410/a75e95d8-6db4-11e5-91a5-97d56c378b80.png)

And it doesn't compile -> Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_NativeInterface", referenced from:"

So you have to set Architectures to standards and Build Active Architecture Only  to Yes like this

![goodbuilds](https://cloud.githubusercontent.com/assets/3285421/10363459/f03c5376-6db4-11e5-9945-7c55938dc595.png)

hope this helps

**Comment by samizzo** [comment]
Ah okay, that's good to know. Basically the architecture should match up everywhere, so if Unity is generating an Xcode project set to arm64, then in the UnityNativePrototype the static library should also be set to arm64.

When I was testing I think I actually forced everything to arm64 to make sure it was all the same, because I wasn't sure what it meant when it had "armv7 arm64" both in there, and I couldn't see how to set what the "active architecture" is. I don't use Xcode that often (also I'm still on Xcode 6). I'll have to update soon, but that means updating OSX as well which I didn't want to do. Ah well!

**Comment by haxpor** [comment]
I believe the problem @ingouackaz was facing might be because of the result `libNativeInterface.a` that XCode generated is for different architecture not mobile.

I re-look at this repository again and I have to go to iOS native project and rebuild it but make sure you select a target to your device (thus arm64, armv7, etc), not simulator (x86, i_386, etc). That aligns with what @samizzo said to make sure Unity generates the proper and correct architecture (device, or simulator). Finally the build result should be fine. :)
